# JuiceLab
# https://github.com/psvm-io/juicelab
# Federico Mattalia

name: juicelab
services:
  www:
    image: juicelab-www
    container_name: juicelab-www
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      juicenet:
        ipv4_address: 10.92.0.2

  kali:
    image: juicelab-kali
    container_name: juicelab-kali
    depends_on:
      - www
    stdin_open: true
    tty: true
    build:
      context: ./kali
      dockerfile: Dockerfile
    volumes:
      - data:/root/data
    restart: always
    networks:
      juicenet:
        ipv4_address: 10.92.0.3

volumes:
  data:

networks:
  juicenet:
    name: juicenet
    ipam:
      driver: default
      config:
        - subnet: 10.92.0.0/24
