# JuiceLab
# https://github.com/psvm-io/juicelab
# Docker Compose file

name: juicelab
services:
  www:
    image: juicelab-www
    container_name: juicelab-www
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      juicenet:
        ipv4_address: ${WWW_IP}

  kali:
    image: juicelab-kali
    container_name: juicelab-kali
    hostname: ${KALI_HOSTNAME}
    depends_on:
      - www
    stdin_open: true
    tty: true
    build:
      context: ./kali
      dockerfile: Dockerfile
    volumes:
      - data:/root/data
    networks:
      juicenet:
        ipv4_address: ${KALI_IP}

volumes:
  data:

networks:
  juicenet:
    name: juicenet
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
